log_dir: logs/evaluations/effnb4
pretrained: null
model_name: efficientnetb4
backbone_name: efficientnetb4
backbone_config:
  num_classes: 2
  inc: 3
  dropout: false
  mode: Original
all_dataset:
- FaceForensics++
- FF-F2F
- FF-DF
- FF-FS
- FF-NT
- FaceShifter
- DeepFakeDetection
- Celeb-DF-v1
- Celeb-DF-v2
- DFDCP
- DFDC
- DeeperForensics-1.0
- UADFV
train_dataset:
- FaceForensics++
test_dataset:
- FaceForensics++
- Celeb-DF-v2
compression: c23
train_batchSize: 8
test_batchSize: 8
workers: 2
frame_num:
  train: 6
  test: 4
resolution: 256
with_mask: false
with_landmark: false
save_ckpt: true
save_feat: false
use_data_augmentation: true
data_aug:
  flip_prob: 0.5
  rotate_prob: 0.5
  rotate_limit:
  - -10
  - 10
  blur_prob: 0.5
  blur_limit:
  - 3
  - 7
  brightness_prob: 0.5
  brightness_limit:
  - -0.1
  - 0.1
  contrast_limit:
  - -0.1
  - 0.1
  quality_lower: 40
  quality_upper: 100
mean:
- 0.5
- 0.5
- 0.5
std:
- 0.5
- 0.5
- 0.5
optimizer:
  type: adam
  adam:
    lr: 0.0002
    beta1: 0.9
    beta2: 0.999
    eps: 1.0e-08
    weight_decay: 0.0005
    amsgrad: false
  sgd:
    lr: 0.0002
    momentum: 0.9
    weight_decay: 0.0005
lr_scheduler: null
nEpochs: 8
start_epoch: 0
save_epoch: 1
rec_iter: 20
logdir: ./logs
manualSeed: 1024
loss_func: cross_entropy
losstype: null
metric_scoring: auc
cuda: true
cudnn: true
