log_dir: logs/evaluations/effnb4_sfdct
pretrained: null
model_name: efficientnetb4_hff
backbone_name: efficientnetb4
dct_channels: 1792
dct_grid: 8
residual_source: blockdct
dct_drop_low_bands: 3
hff_multi_scale: true
hff_use_rsa: true
hff_lr_mult: 3.0
scl_weight: 0.3
scl_margin: 0.3
backbone_config:
  num_classes: 2
  inc: 3
  dropout: false
  mode: Original
all_dataset:
- FaceForensics++
- FF-F2F
- FF-DF
- FF-FS
- FF-NT
- FaceShifter
- DeepFakeDetection
- Celeb-DF-v1
- Celeb-DF-v2
- DFDCP
- DFDC
- DeeperForensics-1.0
- UADFV
train_dataset:
- FaceForensics++
test_dataset:
- FaceForensics++
- Celeb-DF-v2
dataset_json_folder: ./preprocessing/dataset_json
compression: c23
train_batchSize: 32
test_batchSize: 32
workers: 8
frame_num:
  train: 32
  test: 32
resolution: 256
with_mask: false
with_landmark: false
save_ckpt: true
save_feat: false
use_data_augmentation: true
data_aug:
  flip_prob: 0.5
  rotate_prob: 0.5
  rotate_limit:
  - -10
  - 10
  blur_prob: 0.5
  blur_limit:
  - 3
  - 7
  brightness_prob: 0.5
  brightness_limit:
  - -0.1
  - 0.1
  contrast_limit:
  - -0.1
  - 0.1
  quality_lower: 40
  quality_upper: 100
mean:
- 0.5
- 0.5
- 0.5
std:
- 0.5
- 0.5
- 0.5
optimizer:
  type: adam
  adam:
    lr: 0.0002
    beta1: 0.9
    beta2: 0.999
    eps: 1.0e-08
    weight_decay: 0.0005
    amsgrad: false
  sgd:
    lr: 0.0002
    momentum: 0.9
    weight_decay: 0.0005
lr_scheduler: null
nEpochs: 10
start_epoch: 0
save_epoch: 1
rec_iter: 100
logdir: ./logs
manualSeed: 1024
loss_func: cross_entropy
losstype: null
metric_scoring: auc
cuda: true
cudnn: true
